#! /bin/sh

#setxkbmap de
setxkbmap de
xset r rate 200 25
#xmodprobe /home/david/.Xmodmaprc
#xmodmap .Xmodmaprc
sxhkd &

xsetroot -cursor_name arrow

#sh /home/david/p/scripts/batter-status.sh &

#pgrep bspswallow || bspswallow &
#pidof bspswallow || bspswallow &
#bspswallow &

#killall keynav 
#keynav &

killall unclutter
unclutter -root -idle 1 &
#unclutter -root -idle 1 -keystroke &

killall fusuma
fusuma -c ~/.config/fusuma/config_bspwm.yml &

gnome-screensaver &
#gsettings set org.gnome.desktop.interface gtk-theme 'Adwaita-dark'

# no more blackscreen
xset -dpms

###########################################################
## lemonbar
#killall lemonbar
#killall lemonbar.sh
#~/.config/lemonbar/lemonbar.sh | lemonbar  -p -b &

bspc monitor HDMI1 -d 1 2 3 4 5 6 7 8 9 10
#bspc monitor eDP1 --remove
###########################################################
## polybar
export MONITOR="HDMI-1"
$HOME/.config/polybar/launch.sh

###########################################################
## wallpapers

feh ~/Pictures/wp/not_black.png --bg-fill
#feh ~/Pictures/wp/lake.jpg --bg-fill
#feh ~/Pictures/wp/black.png --bg-fill
#feh ~/Pictures/wp/surface.jpg --bg-fill
#feh ~/Pictures/wp/mountain.jpg --bg-fill
#feh ~/Pictures/wp/duo.jpg --bg-fill
###########################################################

##########################################################
#my_laptop_external_monitor=$(xrandr --query | grep 'HDMI-1')
#if [[ $my_laptop_external_monitor = *connected* ]]; then
#	touch ~/myfile
#	#xrandr --output eDP1 --mode 1920x1080 --rotate normal --output HDMI1 --primary --mode 2560x1080 --rotate normal --right-of eDP1
#	xrandr --output HDMI-1 --primary --mode 2560x1080 --rotate normal 
#	bspc monitor eDP-1 -d 1 2 3 4 5
#	bspc monitor HDMI-1 -d 6 7 8 9 10
##	~/.config/lemonbar/lemonbar2.sh | lemonbar  -p -b &
#	feh --bg-fill ~/Pictures/wp/gal.jpg ~/Pictures/wp/clean.jpg 
#else
#	#bspc monitor -d I II III IV V VI VII VIII IX X
#	bspc monitor -d 1 2 3 4 5 6 7 8 9 10
#	#feh --bg-fill ~/Pictures/wp/mountain2.jpg 
#	feh --bg-fill ~/Pictures/wp/not_black.png 
#fi
##########################################################

bspc config border_width         2
bspc config window_gap           0

bspc config bottom_padding       20

bspc config split_ratio          0.5
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config single_monocle       true
bspc config automatic_scheme     alternate


# bspc config normal_border_color "#817f7f"
# bspc config focused_border_color "#ff0000" 
#bspc config focused_border_color "#C5C8C6"
bspc config normal_border_color "#1D1F21"
bspc config focused_border_color "#A54242"


bspc rule -a Zathura state=tiled
bspc rule -a retroarch state=tiled
bspc rule -a stellarium state=tiled

export _JAVA_AWT_WM_NONREPARENTING=1

## default values
#bspc config swallow_first_click  false
#bspc config center_pseudo_tiled  true


###########################################################
## xset
xset r rate 200 30
###########################################################
###########################################################
## input handling

# get id of intpudevice
ID=$(xinput list|grep touch -i|sed -nr 's/.*id=([0-9]*).*/\1/p')

# get ids for settings
IN_NAT=$(xinput list-props $ID|grep Natural|grep -v "Default" |sed -nr 's/.*\(([0-9][0-9][0-9])\).*/\1/p')
IN_TAP=$(xinput list-props $ID|grep "Tapping Enabled"|grep -v "Default" |sed -nr 's/.*\(([0-9][0-9][0-9])\).*/\1/p')
IN_MID=$(xinput list-props $ID|grep "Middle"|grep -v "Default" |sed -nr 's/.*\(([0-9][0-9][0-9])\).*/\1/p')

# set settings
xinput set-prop $ID $IN_NAT 1
xinput set-prop $ID $IN_TAP 1
xinput set-prop $ID $IN_MID 1
###########################################################





###########################################################
## no longer used

### xinput set-button-map 17 1 2 3 5 4 6 7 

#xset s 0 0 # prohibit screen from going black
#killall unclutter

# bspc rule -a Gimp desktop='^8' state=floating follow=on
# bspc rule -a Chromium desktop='^2'
# bspc rule -a mplayer2 state=floating
# bspc rule -a Kupfer.py focus=on
# bspc rule -a Screenkey manage=off
###########################################################
setxkbmap -option altwin:swap_lalt_lwin
polybar-msg cmd hide
bspc config bottom_padding 0
