#! /bin/sh

# settings
## xset
xset b off # deactivate bell
xset -dpms # disable powermanagement
xset s off # deactivate screensaver
xset r rate 200 25 # set retrigger rate

## set keyboard
setxkbmap de # language
setxkbmap -option caps:super # caps

## apply Xresources
xrdb -merge ~/.Xresources

## set cursor
xsetroot -cursor_name arrow

## set bspwm monitors
if [[ $(xrandr|grep "HDMI1 conn") ]];then
	xrandr --output HDMI1 --above eDP1
	xrandr --output HDMI1 --primary --auto

	for monitor in {HDMI1,eDP1};do
		for pad in { bottom_padding, left_padding, top_padding, right_padding };do
			bspc config -m $monitor $pad 0
		done
	done

	bspc monitor HDMI1  -d 1 2 3 4 5 6 7 8 9 10
	bspc monitor eDP1  -d s1 s2 s3
	bspc monitor -f HDMI1
else
	bspc monitor eDP1  -d 1 2 3 4 5 6 7 8 9 10
fi

killall unclutter
unclutter -root -idle 1 --start-hidden &

## bspc configuration
bspc config border_width         2
bspc config window_gap           0

bspc config bottom_padding       20

bspc config split_ratio          0.5
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config single_monocle       true
bspc config automatic_scheme     alternate

bspc config normal_border_color "#1d1f21"
bspc config focused_border_color "#a54242"

bspc rule -a Zathura state=tiled
bspc rule -a retroarch state=tiled
bspc rule -a stellarium state=tiled


# polybar
killall polybar
$HOME/.config/polybar/launch.sh


# wallpaper
feh ~/p/images/background/back.png --bg-fill


# touchpad config
## get id of intpudevice
ID=$(xinput list|grep touch -i|sed -nr 's/.*id=([0-9]*).*/\1/p')
## get ids for settings
IN_NAT=$(xinput list-props $ID|grep Natural|grep -v "Default" |sed -nr 's/.*\(([0-9][0-9][0-9])\).*/\1/p')
IN_TAP=$(xinput list-props $ID|grep "Tapping Enabled"|grep -v "Default" |sed -nr 's/.*\(([0-9][0-9][0-9])\).*/\1/p')
IN_MID=$(xinput list-props $ID|grep "Middle"|grep -v "Default" |sed -nr 's/.*\(([0-9][0-9][0-9])\).*/\1/p')
## set settings
xinput set-prop $ID $IN_NAT 1
xinput set-prop $ID $IN_TAP 1
xinput set-prop $ID $IN_MID 1


# set bar
polybar-msg cmd hide
bspc config bottom_padding 0


# start hotkey daemon
killall sxhkd
sxhkd &
