foreground #d0d0d0
background #000000

color0 #000000
color8 #808080

color1 #ff0000
color9 #ff0000

color2 #33ff00
color10 #33ff00

color3 #ff0099
color11 #ff0099

color4 #0066ff
color12 #0066ff

color5 #cc00ff
color13 #cc00ff

color6 #00ffff
color14 #00ffff

color7 #d0d0d0
color15 #ffffff

enable_audio_bell no
font_size 11.0
remember_window_size  no


map kitty_mod+plus     change_font_size all +2.0
map kitty_mod+minus     change_font_size all -2.0
map kitty_mod+backspace change_font_size all 0
map kitty_mod+i set_colors --configured ~/.dotfiles/kitty/.config/kitty/hacker.conf
map kitty_mod+o set_colors --configured ~/.dotfiles/kitty/.config/kitty/kitty.conf

font_family      Source Code Pro

enable_audio_bell no

clipboard_control write-clipboard read-clipboard
