swipe:
  3: 
    left: 
      command: 'xdotool key alt+Tab'
    right: 
      command: 'xdotool key alt+Shift+Tab'
    up: 
      command: 'xdotool key super'
    down: 
      command: 'xdotool key super+d'
  4:
    left: 
      command: 'xdotool key ctrl+Page_Up'
    right: 
      command: 'xdotool key ctrl+Page_Down'
    up: 
      command: 'xdotool key ctrl+alt+Down'
    down: 
      command: 'xdotool key ctrl+alt+Up'
pinch:
  2:
    in:
      command: 'xdotool key ctrl+plus'
    out:
      command: 'xdotool key ctrl+minus'
  4:
    in:
      command: 'xdotool key super'
    out:
      command: 'xdotool key super+a'

threshold:
  swipe: 0.4
  pinch: 0.4

interval:
  swipe: 0.8
  pinch: 5
