swipe:
  3: 
    left: 
      command: 'bspc node -f west'
    right: 
      command: 'bspc node -f east'
    up: 
      command: 'bspc node -f north'
    down: 
      command: 'bspc node -f south'
  4:
    left: 
      command: 'xdotool key ctrl+Page_Up'
    right: 
      command: 'xdotool key ctrl+Page_Down'
    up: 
      command: 'bspc desktop -f next.local'
    down: 
      command: 'bspc desktop -f prev.local'
pinch:
  2:
    in:
      command: 'xdotool key ctrl+plus'
    out:
      command: 'xdotool key ctrl+minus'
  3:
    in:
      command: 'firefox'
    out:
      command: 'gnome-terminal'
  4:
    in:
      command: ''
    out:
      command: ''

threshold:
  swipe: 0.4
  pinch: 0.4

interval:
  swipe: 0.8
  pinch: 5
